function BrandFactory(name, logoPath) {
  return { name, logoPath };
}

export const GearBrandMap = {
  'PEDALS': [
    BrandFactory('Wampler', 'wampler-pedal.png'),
    BrandFactory('Electro-Harmonix', 'electro-harmonic-pedal.png'),
    BrandFactory('Behringer', 'behringer-pedal.png'),
    BrandFactory('MXR/Dunlop', 'mxr-pedal.png'),
    BrandFactory('TC Electronic', 'tc-electronic-pedal.png'),
    BrandFactory('Carl Martin', 'carl-martin-pedal.png'),
    BrandFactory('Line 6', 'line-6-pedal.png'),
    BrandFactory('Xotic Effects', 'xotic-pedal.png'),
    BrandFactory('Keeley', 'keeley-pedal.png'),
    BrandFactory('Tortuga Effects', 'toruga-pedal.png'),
    BrandFactory('Boss', 'boss-pedal.png'),
    BrandFactory('Pigtronix', 'pigtronix-pedal.png'),
    BrandFactory('Tech 21', 'tech-21-pedal.png'),
    BrandFactory('JHS Pedals', 'jhs-pedal.png'),
    BrandFactory('Way Huge', 'way-huge-pedal.png'),
    BrandFactory('EWS', 'ews-pedal.png'),
    BrandFactory('Pro Co Rat', 'pro-rat-cat-pedal.png'),
    BrandFactory('Mooer', 'mooer-pedal.png'),
    BrandFactory('Digitech', 'digitech-pedal.png'),
    BrandFactory('Amptweaker *', 'amptweaker-pedal.png'),
    BrandFactory('AMT *', 'amt-pedal.png'),
    BrandFactory('Strymon *', 'strymon-pedal.png'),
    BrandFactory('Seymour Duncan *', 'seymour-duncan-pedal.png'),
  ],
  'AMPS': [
    BrandFactory('Krank', 'krank-amp.png'),
    BrandFactory('Blackstar', 'blackstar-amp.png'),
    BrandFactory('Marshall', 'marshall-amp.png'),
    BrandFactory('Line 6', 'line-6-amp.png'),
    BrandFactory('Roland', 'cube-amp.png'),
    BrandFactory('Behringer', 'behringer-amp.png'),
    BrandFactory('Orange', 'orange-amp.png'),
    BrandFactory('EVH', 'evh-amp.png'),
    BrandFactory('Peavey', 'peavy-amp.png'),
  ],
  'PICKUPS': [
    BrandFactory('Fender', 'fender-pickups.png'),
    BrandFactory('Gibson', 'gibson-pickups.png'),
    BrandFactory('Rio Grande', 'rio-grande-pickups.png'),
    BrandFactory('EMG', 'emg-pickup.png'),
    BrandFactory('TV Jones', 'tv-jones-pickup.png'),
    BrandFactory('Lace', 'lace-pickups.png'),
    BrandFactory('DiMarzio', 'dimarzio-pickup.png'),
    BrandFactory('PRS', 'prs-pickup.png'),
    BrandFactory('EVH', 'evh-pickups.png'),
    BrandFactory('Seymour Duncan', 'seymour-pickup.png'),
  ],
  'TUBES': [
    BrandFactory('Mullard', 'mullard-tube.png'),
    BrandFactory('JJ', 'jj-tube.png'),
    BrandFactory('Sovtek', 'sovtek-tube.png'),
    BrandFactory('Tung Sol', 'tung-sol-tube.png'),
    BrandFactory('Winged “C”', 'winged-c-tube.png'),
    BrandFactory('Electro-Harmonix', 'electro-harmonix-tube.png'),
  ],
  'STAGE': [
    BrandFactory('MBT', 'mbt-lighting.png'),
    BrandFactory('American DJ', 'american-dj-lighting.png'),
  ],
};
